let dataScene = [
    {
        colorbox: 0x2e2e2e,
        // texture2: "",
        width: 1,
        height: 1,
        depth: 1,
        x: -6.5,
        y: 1 / 2,
        z: -6.5,
      },
      {
        colorbox: 0x2e2e2e,
        // texture2: "",
        width: 1,
        height: 1,
        depth: 1,
        x: -5.5,
        y: 1 / 2,
        z: -6.5,
      },
    
      {
        colorbox: 0x2e2e2e,
        // texture2: "",
        width: 1,
        height: 1,
        depth: 1,
        x: -6.5,
        y: 1 / 2,
        z: -5.5,
      },
      {
        colorbox: 0x2e2e2e,
        // texture2: "",
        width: 1,
        height: 1,
        depth: 1,
        x: -6.5,
        y: 1 / 2,
        z: -4.5,
      },
      {
        colorbox: 0x2e2e2e,
        // texture2: "",
        width: 1,
        height: 1,
        depth: 1,
        x: -3.5,
        y: 1 / 2,
        z: -6.5,
      },
    
      {
        colorbox: 0x5c351c,
        // texture2: "",
        width: 1,
        height: 1,
        depth: 3,
        x: -1.5,
        y: 1 / 2,
        z: -3.5,
      },
    
      {
        colorbox: 0x5c351c,
        // texture2: "",
        width: 3,
        height: 1,
        depth: 1,
        x: -2.5,
        y: 1 / 2,
        z: -2.5,
      },
      {
        colorbox: "",
        // texture2: "lavabo2",
        width: .8,
        height: 1,
        depth: 2,
        x: -6.5,
        y: 1 / 2,
        z: 4.75
      },
      {
        colorbox: 0x5c351c,
        // texture2: "",
        width: 1,
        height: 1,
        depth: 1,
        x: 6.5,
        y: 1 / 2,
        z: 6.5,
      },
      {
        colorbox: 0x5c351c,
        // texture2: "",
        width: 1,
        height: 1,
        depth: 1,
        x: 6.5,
        y: 1 / 2,
        z: 2.5,
      },
      {
        colorbox: 0xff0000,
        // texture2: "lit",
        width: 4,
        height: 0.75,
        depth: 3,
        x: 5,
        y: 0.75 / 2,
        z: 4.5,
      },
      {
        colorbox: 0x6b452a,
        // texture2: "meuble salon",
        width: 1,
        height: 0.5,
        depth: 3,
        x: 6.5,
        y: 0.5 / 2,
        z: -3.5,
      },
      {
        colorbox: 0x000000,
        // texture2: "canap",
        width: 1.5,
        height: 1,
        depth: 3,
        x: 1.5,
        y: 1 / 2,
        z: -3.5,
      },
      {
        colorbox: 0x5c351c,
        // texture2: "table Basse",
        width: 1.25,
        height: 0.5,
        depth: 1.25,
        x: 3.5,
        y: 0.5 / 2,
        z: -3.5,
      },
      
      {
        colorbox: 0x5c351c,
        // texture2: "armoire",
        width: 1,
        height: 2,
        depth: 2,
        x: -6.5,
        y: 2 / 2,
        z: 6.25,
      },{
        colorbox: 0x556570,
        // texture2: "mur sans porte",
        width: 6,
        height: 3,
        depth: .3,
        x: -4.5,
        y: 3 / 2,
        z: 2,
      },
      {
        colorbox: 0x556570,
        // texture2: "mur avec porte 1",
        width: .3,
        height: 3,
        depth: 2.3,
        x: -1.5,
        y: 3 / 2,
        z: 3,
      },
      {
        colorbox: 0x556570,
        // texture2: "mur avec porte 2",
        width: .3,
        height: 3,
        depth: 1.3,
        x: -1.5,
        y: 3 / 2,
        z: 6.4,
      },
      {
        colorbox: 0x556570,
        // texture2: "mur au dessus porte",
        width: .3,
        height: .5,
        depth: 3,
        x: -1.5,
        y: 2.75,
        z: 4.4,
      },



]

export default dataScene