let data = [
  //cuisine
  //meubles useless
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 1,
    height: 1,
    depth: 1,
    x: -6.5,
    y: 1 / 2,
    z: -6.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 1,
    height: 1,
    depth: 1,
    x: -5.5,
    y: 1 / 2,
    z: -6.5,
  },

  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 1,
    height: 1,
    depth: 1,
    x: -6.5,
    y: 1 / 2,
    z: -5.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 1,
    height: 1,
    depth: 1,
    x: -6.5,
    y: 1 / 2,
    z: -4.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 1,
    height: 1,
    depth: 1,
    x: -3.5,
    y: 1 / 2,
    z: -6.5,
  },

  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 1,
    height: 1,
    depth: 3,
    x: -1.5,
    y: 1 / 2,
    z: -3.5,
  },

  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 3,
    height: 1,
    depth: 1,
    x: -2.5,
    y: 1 / 2,
    z: -2.5,
  },

  // interactions
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 0.3,
    height: 1,
    depth: 0.3,
    x: -3.5,
    y: 1,
    z: -6.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "four",
    width: 1,
    height: 1,
    depth: 1,
    x: -6.5,
    y: 1 / 2,
    z: -3.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "four",
    width: 1,
    height: 1,
    depth: 1,
    x: -6.5,
    y: 1.5,
    z: -3.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "frigo",
    width: 1,
    height: 2,
    depth: 1,
    x: -6.5,
    y: 2 / 2,
    z: -2.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "hotte",
    width: 1,
    height: 0.5,
    depth: 1,
    x: -6.5,
    y: 2,
    z: -5.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "plaque",
    width: 1,
    height: 0.5,
    depth: 1,
    x: -6.5,
    y: 0.8,
    z: -5.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "evier",
    width: 1,
    height: 1,
    depth: 1,
    x: -4.5,
    y: 1 / 2,
    z: -6.5,
  },

  // côté chambre
  //useless
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 1,
    height: 1,
    depth: 1,
    x: 6.5,
    y: 1 / 2,
    z: 6.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 1,
    height: 1,
    depth: 1,
    x: 6.5,
    y: 1 / 2,
    z: 2.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "lit",
    width: 4,
    height: 0.75,
    depth: 3,
    x: 5,
    y: 0.75 / 2,
    z: 4.5,
  },
  // interactions
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 0.2,
    height: 1,
    depth: 0.2,
    x: 6.5,
    y: 1,
    z: 6.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "",
    width: 0.2,
    height: 1,
    depth: 0.2,
    x: 6.5,
    y: 1,
    z: 2.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "prise",
    width: 0.2,
    height: 0.2,
    depth: 0.2,
    x: 7,
    y: 0.5,
    z: 1.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "radiateur",
    width: 1.2,
    height: 0.75,
    depth: 0.4,
    x: 4.5,
    y: 1 / 2,
    z: 7,
  },
  //salon
  //useless
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "meuble salon",
    width: 1,
    height: 0.5,
    depth: 3,
    x: 6.5,
    y: 0.5 / 2,
    z: -3.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "canap",
    width: 1.5,
    height: 1,
    depth: 3,
    x: 1.5,
    y: 1 / 2,
    z: -3.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "table Basse",
    width: 1.25,
    height: 0.5,
    depth: 1.25,
    x: 3.5,
    y: 0.5 / 2,
    z: -3.5,
  },
  //interaction
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "prise",
    width: 0.2,
    height: 0.2,
    depth: 0.2,
    x: 7,
    y: 0.35,
    z: -1.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "TV",
    width: 0.4,
    height: 1.5,
    depth: 2.7,
    x: 6.5,
    y: 2 / 2,
    z: -3.5,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "fenetre",
    width: 3,
    height: 2,
    depth: 0.7,
    x: 3.5,
    y: 1.7,
    z: -7.2,
  },
  // salle de bain
  //useless

  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "WC",
    width: 1,
    height: 1,
    depth: 0.75,
    x: -6.5,
    y: 1 / 2,
    z: 3,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "armoire",
    width: 1,
    height: 2,
    depth: 2,
    x: -6.5,
    y: 2 / 2,
    z: 6.25,
  },
  // interaction
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "douche",
    width: 1.5,
    height: 2.5,
    depth: 1.5,
    x: -4.25,
    y: 2.5 / 2,
    z: 6.25,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "lavabo2",
    width: 1,
    height: 1,
    depth: 2,
    x: -6.5,
    y: 1 / 2,
    z: 4.75,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "prise",
    width: 0.2,
    height: 0.2,
    depth: 0.2,
    x: -7,
    y: 1.25,
    z: 3.75,
  },
  //murs
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "mur sans porte",
    width: 6,
    height: 3,
    depth: .3,
    x: -4.5,
    y: 3 / 2,
    z: 2,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "mur avec porte 1",
    width: .3,
    height: 3,
    depth: 2.3,
    x: -1.5,
    y: 3 / 2,
    z: 3,
  },
  {
    texture: "./../assets/dark_brick_wall.jpg",
    // texture2: "mur avec porte 2",
    width: .3,
    height: 3,
    depth: 1.3,
    x: -1.5,
    y: 3 / 2,
    z: 6.4,
  },
  {
    texture: "../assets/dark_brick_wall.jpg",
    // texture2: "mur au dessus porte",
    width: .3,
    height: .5,
    depth: 3,
    x: -1.5,
    y: 2.75,
    z: 4.4,
  },

];
export default data;

// Object { x: 0, y: 2.5, z: -10 }
// Object { x: 0, y: 2.5, z: 10 }
// Object { x: -10, y: 2.5, z: 0 }
// Object { x: 10, y: 2.5, z: 0 }
